language: objective-c
before_install: scripts/bootstrap
script:
    - xctool -project Overcoat.xcodeproj -scheme "Overcoat iOS Tests" -sdk iphonesimulator -configuration Release test
    - xctool -project Overcoat.xcodeproj -scheme "Overcoat Mac Tests" -sdk macosx -configuration Release test
