language: objective-c
before_install: gem install cocoapods
script:
    - xctool -workspace Overcoat.xcworkspace -scheme "Overcoat iOS" -sdk iphonesimulator -configuration Release test -test-sdk iphonesimulator7.0
